# TOON Protocol -- Nix Flake for Reproducible Docker Builds
#
# This flake defines a reproducible build pipeline that produces deterministic
# Docker images with identical content hashes (and thus identical PCR values)
# across independent builds. This is the foundation of the TEE attestation
# trust model (FR-TEE-5): if builds are reproducible, operators can verify
# that the code running inside an enclave matches the expected source.
#
# Outputs:
#   - packages.x86_64-linux.docker-image: Deterministic Docker image for Oyster CVM
#   - devShells.x86_64-linux.default: Development shell with Node.js 20 + pnpm
#
# Usage:
#   nix build .#docker-image           # Build the Docker image
#   docker load < result               # Load into Docker daemon
#   nix develop                        # Enter dev shell with pinned tools
#
# Reproducibility guarantees:
#   - nixpkgs pinned to a specific commit hash (via flake.lock)
#   - All dependencies resolved from the Nix store (content-addressed)
#   - No mutable package managers used during image construction
#   - Image timestamps fixed to epoch 0
#   - flake.lock pins all transitive inputs
#
# NOTE: flake.lock is auto-generated by `nix flake lock` and pins all inputs
# to specific content hashes. It must be committed to version control.
{
  description = "TOON Protocol -- ILP-gated Nostr relay (reproducible Docker build)";

  inputs = {
    # Pin nixpkgs to a specific commit for full reproducibility.
    # This commit is from the nixos-24.05 stable branch, ensuring all packages
    # (Node.js 20, supervisord, coreutils) are at known-good versions.
    nixpkgs.url = "github:NixOS/nixpkgs/b134951a4c9f3c995fd7be05f3243f8ecd65d798";
  };

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };

      # Build derivation: compile the TOON monorepo from source.
      # This runs pnpm install (frozen lockfile) and builds all packages,
      # then deploys only production dependencies for the Docker image.
      productionBuild = pkgs.stdenv.mkDerivation {
        name = "toon-production";
        src = ./.;

        nativeBuildInputs = [
          pkgs.nodejs_20
          pkgs.nodePackages.pnpm
          pkgs.python3
          pkgs.gnumake
          pkgs.gcc
        ];

        # Disable network access during build (Nix sandbox enforces this).
        # All dependencies must come from the pnpm lockfile and Nix store.
        buildPhase = ''
          export HOME=$TMPDIR

          # Install all dependencies (including devDependencies for build)
          pnpm install --frozen-lockfile --offline

          # Build all packages in the monorepo
          pnpm -r build

          # Build the Docker entrypoint package
          cd docker && pnpm run build && cd ..
        '';

        installPhase = ''
          # Deploy production-only dependencies (no devDeps, no symlinks)
          pnpm --filter @toon-protocol/docker deploy --prod $out

          # Copy package.json files and built artifacts for all packages
          mkdir -p $out/packages/bls $out/packages/client $out/packages/core \
                   $out/packages/relay $out/packages/sdk $out/packages/town

          for pkg in bls client core relay sdk town; do
            cp packages/$pkg/package.json $out/packages/$pkg/
            cp -r packages/$pkg/dist $out/packages/$pkg/
          done

          cp -r docker/dist $out/docker/
          cp tsconfig.json $out/
        '';
      };

      # Docker image definition (imported from docker/Dockerfile.nix)
      # The Nix expression in Dockerfile.nix declares the image contents
      # using Nix derivations; this flake orchestrates the build.
      dockerImage = import ./docker/Dockerfile.nix {
        inherit pkgs;
        productionDeps = productionBuild;
      };

    in
    {
      # Primary output: deterministic Docker image for Oyster CVM deployment.
      # Build with: nix build .#docker-image
      # Load with: docker load < result
      packages.${system}.docker-image = dockerImage;

      # Default package alias
      packages.${system}.default = dockerImage;

      # Development shell with pinned Node.js and pnpm for local development.
      # Enter with: nix develop
      devShells.${system}.default = pkgs.mkShell {
        buildInputs = [
          pkgs.nodejs_20
          pkgs.nodePackages.pnpm
          pkgs.python3
        ];

        shellHook = ''
          echo "TOON dev shell (Node.js $(node --version), pnpm $(pnpm --version))"
        '';
      };
    };
}
